<% require "dotenv"; Dotenv.load(".env") %>

service: demo-node-astro
image: gambala/demo-node-astro
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: node-astro.gambala.pro
  app_port: 4321
  healthcheck:
    interval: 10
    path: /
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: arm64
